Re-factor building instructions alot

diff --git a/grafana/Dockerfile b/grafana/Dockerfile
--- a/grafana/Dockerfile
+++ b/grafana/Dockerfile
@@ -1,33 +1,31 @@
 FROM grafana/grafana:7.3.6
 
+SHELL [ "/usr/bin/env", "bash", "-ueo", "pipefail", "-c"]
+
 # Use root to install
 USER root
 
-RUN \
-    apk add --no-cache ca-certificates wget && \
-    update-ca-certificates
+RUN apk --no-cache upgrade
+RUN apk add --quiet --no-cache \
+    ca-certificates wget curl jq udev ttf-opensans chromium; \
+    update-ca-certificates;
 
 # Install all available plugins
 RUN \
-  apk add curl jq && \
-  for plugin in $(curl -s https://grafana.net/api/plugins?orderBy=name | jq '.items[] | select(.internal == false) | select(.slug != "grafana-image-renderer" and .slug != "doitintl-bigquery-datasource") | .slug' | tr -d '"' | sort); \
-      do grafana-cli plugins install $plugin; \
+  for plugin in $(curl -s https://grafana.net/api/plugins?orderBy=name | \
+    jq '.items[] | select(.internal == false) | select(.slug != "grafana-image-renderer" and .slug != "doitintl-bigquery-datasource") | .slug' \
+    | tr -d '"' | sort); \
+      do \
+      echo "${plugin}"; \
+      grafana-cli plugins install "${plugin}" || echo "failed ${plugin}"; \
   done
 
 # Install Image Renderer plugin
-RUN \
-    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
-    echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
-    echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
-    apk --no-cache  upgrade && \
-    apk add --no-cache udev ttf-opensans chromium && \
-    rm -rf /tmp/* && \
-    rm -rf /usr/share/grafana/tools/phantomjs;
+RUN rm -vrf /usr/share/grafana/tools/phantomjs
 
 ENV GF_RENDERER_PLUGIN_CHROME_BIN="/usr/bin/chromium-browser"
 
-RUN \
-    grafana-cli \
+RUN grafana-cli \
         plugins install grafana-image-renderer;
 
 RUN \
